Added hdr parser.
playcanvas/engine pull request #2956
Opened 2021-03-11 12:38 UTC by figo2264

Fixes #

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

I've added HdrParser from playcanvas viewer to the original engine.

Just wonder why this good feature is not included.

2021-03-11 13:41 UTC, yaustar commented on src/resources/texture.js
> +import { HdrParser} from "./parser/texture/hdr";
```suggestion
import { HdrParser } from "./parser/texture/hdr";
```

2021-03-11 13:41 UTC, yaustar commented on src/resources/texture.js
> +import { HdrParser} from "./parser/texture/hdr";
Lint fix

2021-03-11 14:39 UTC, willeastcott commented
@slimbuck will review this on Monday. 😄

2021-03-13 13:01 UTC, slimbuck requested changes
Hi @figo2264 and thanks for this PR!

@willeastcott, just checking you're happy for us to make this HDR parser part of the engine? It would mean we can remove the two versions we have (in the viewer and engine examples), but will increase engine size.

2021-03-13 14:31 UTC, willeastcott commented on src/resources/parser/texture/hdr.js
> +function Reader(data) {
Can you make this an ES6 class please?

2021-03-13 14:32 UTC, willeastcott commented
I'm OK adding this to the engine if you are @slimbuck. It's not huge and it is being used by the viewer. In future, I'm hoping tree shaking will make it less relevant how big the engine is anyway.

2021-03-13 23:52 UTC, Maksims commented
Will it be possible to add support for HDR textures in Editor with help of this PR?

2021-03-14 21:33 UTC, willeastcott commented
@Maksims That's actually non-trivial, because currently, HDR images are auto-converted to RGBM PNGs on import into the Editor. So we'd need to add support for HDR import options that allow them to be treated as a runtime format.

2021-03-16 22:59 UTC, slimbuck commented
Closing this PR in favour of #2973, which makes a few additional changes.

2021-03-16 22:59 UTC, closed without merging